id: I1CE4AA1B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T05:17:50+00:00'
last_modified: '2022-06-08T16:15:01.551153+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5580
  title: གཡུང་དྲུང་བོན་གྱི་གྲུབ་མཐའ་སྤྱི་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    CD8C:
      image_group_id: I3CN5582
      title: Volume 1 of g.yung drung bon gyi grub mtha' spyi bshad/
      total_pages: 314
      order: 1
      base_file: CD8C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
