id: opecha:P007045
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5580
  title: གཡུང་དྲུང་བོན་གྱི་གྲུབ་མཐའ་སྤྱི་བཤད།
  volume:
    e191214e2aca409ab57256f219ff01a5:
      image_group_id: I3CN5582
      title: Volume 1 of g.yung drung bon gyi grub mtha' spyi bshad/
      volume_number: 1
      total_pages: 314
  author: ''
ebook_metadata:
  title: གཡུང་དྲུང་བོན་གྱི་གྲུབ་མཐའ་སྤྱི་བཤད།
  author: ''
  sku: P007045
  cover: cover.jpg
  layers:
  - pagination
