id: P007045
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN5580
  title: གཡུང་དྲུང་བོན་གྱི་གྲུབ་མཐའ་སྤྱི་བཤད།
  author: ''
  volumes:
    e191214e2aca409ab57256f219ff01a5:
      image_group_id: I3CN5582
      title: Volume 1 of g.yung drung bon gyi grub mtha' spyi bshad/
      volume_number: 1
      total_pages: 314
      base_file: v001.txt
