id: P007045
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5580
  title: གཡུང་དྲུང་བོན་གྱི་གྲུབ་མཐའ་སྤྱི་བཤད།
  author: ''
  volumes:
    43ff2693e42e4367bb73e10069e6d2f6:
      image_group_id: I3CN5582
      title: ''
      volume_number: 1
      total_pages: 314
ebook_metadata:
  title: གཡུང་དྲུང་བོན་གྱི་གྲུབ་མཐའ་སྤྱི་བཤད།
  author: ''
  sku: P007045
  cover: cover.jpg
  layers:
  - pagination
